from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from io import BytesIO

def create_contract_report(filename, verdict, risk_score, summary, risks):
    """
    Generates a PDF report for the contract analysis.

    Args:
        filename (str): The name of the file being analyzed.
        verdict (str): The final verdict (ACCEPT, REJECT, CAUTION).
        risk_score (int): The calculated risk score (0-100).
        summary (str): The executive summary of the analysis.
        risks (list): A list of risk dictionaries or objects.

    Returns:
        BytesIO: A BytesIO object containing the generated PDF data.
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []

    # --- Title ---
    title_style = ParagraphStyle(
        'Title',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor("#1E88E5"),
        spaceAfter=20
    )
    story.append(Paragraph("ShouldISignThis? - Contract Analysis", title_style))
    story.append(Paragraph(f"File: {filename}", styles["Normal"]))
    story.append(Spacer(1, 20))

    # --- Verdict Section ---
    verdict_color = colors.green if verdict == "ACCEPT" else colors.orange if verdict == "CAUTION" else colors.red
    
    verdict_style = ParagraphStyle(
        'Verdict',
        parent=styles['Heading2'],
        fontSize=18,
        textColor=verdict_color,
        spaceAfter=10
    )
    story.append(Paragraph(f"VERDICT: {verdict}", verdict_style))
    story.append(Paragraph(f"Risk Score: {risk_score}/100", styles["Heading3"]))
    story.append(Spacer(1, 10))

    # --- Summary ---
    story.append(Paragraph("Executive Summary", styles["Heading2"]))
    story.append(Paragraph(summary, styles["Normal"]))
    story.append(Spacer(1, 20))

    # --- Key Risks ---
    if risks:
        story.append(Paragraph("Key Risks Identified", styles["Heading2"]))
        
        # Create a table for risks
        data = [["Risk", "Severity", "Description"]]
        for r in risks:
            # Handle different risk formats (obj or dict)
            risk_name = r.get('risk', 'Unknown Risk') if isinstance(r, dict) else getattr(r, 'risk', 'Unknown')
            severity = r.get('severity', 'Medium') if isinstance(r, dict) else getattr(r, 'severity', 'Medium')
            # Use 'explanation' as primary field, fallback to 'description'
            desc = r.get('explanation', '') if isinstance(r, dict) else getattr(r, 'explanation', '')
            if not desc:
                desc = r.get('description', '') if isinstance(r, dict) else getattr(r, 'description', '')
            
            # Wrap text in Paragraphs to enable wrapping
            data.append([
                Paragraph(str(risk_name), styles["Normal"]),
                Paragraph(str(severity), styles["Normal"]),
                Paragraph(str(desc), styles["Normal"])
            ])

        # Table width must be <= 468pt (612 - 72*2)
        table = Table(data, colWidths=[100, 60, 300])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#f0f0f0")),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.white),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('WORDWRAP', (0, 0), (-1, -1), True),
        ]))
        story.append(table)

    # --- Footer ---
    story.append(Spacer(1, 40))
    footer_style = ParagraphStyle('Footer', parent=styles['Normal'], fontSize=8, textColor=colors.gray)
    story.append(Paragraph("Generated by ShouldISignThis? AI Consensus Engine. Not legal advice.", footer_style))

    doc.build(story)
    buffer.seek(0)
    return buffer

def create_comparison_report(filename_a, filename_b, comparison_result, verdict_a, verdict_b):
    """
    Generates a PDF report for the contract comparison.

    Args:
        filename_a (str): Name of Contract A.
        filename_b (str): Name of Contract B.
        comparison_result (dict): The output from the Arbiter agent.
        verdict_a (dict): The verdict for Contract A.
        verdict_b (dict): The verdict for Contract B.

    Returns:
        BytesIO: A BytesIO object containing the generated PDF data.
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []

    # --- Title ---
    title_style = ParagraphStyle(
        'Title',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor("#1E88E5"),
        spaceAfter=20
    )
    story.append(Paragraph("ShouldISignThis? - Contract Face-Off", title_style))
    story.append(Paragraph(f"Comparing: {filename_a} vs {filename_b}", styles["Normal"]))
    story.append(Spacer(1, 20))

    # --- Scoreboard ---
    story.append(Paragraph("Risk Score Comparison", styles["Heading2"]))
    
    data = [
        ["Contract", "Risk Score", "Verdict"],
        [filename_a, f"{verdict_a.get('risk_score')}/100", verdict_a.get('verdict')],
        [filename_b, f"{verdict_b.get('risk_score')}/100", verdict_b.get('verdict')]
    ]
    
    table = Table(data, colWidths=[250, 80, 100])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#f0f0f0")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
    ]))
    story.append(table)
    story.append(Spacer(1, 20))

    # --- Summary ---
    story.append(Paragraph("Analysis Summary", styles["Heading2"]))
    story.append(Paragraph(comparison_result.get('comparison_summary', ''), styles["Normal"]))
    story.append(Spacer(1, 20))

    # --- Key Differences ---
    story.append(Paragraph("Key Differences", styles["Heading2"]))
    
    # Use Paragraphs for table cells to enable wrapping
    normal_style = styles["Normal"]
    small_style = ParagraphStyle('Small', parent=styles['Normal'], fontSize=8, leading=10)
    
    diff_data = [[
        Paragraph("Category", styles["Heading4"]),
        Paragraph("Risk Assessment", styles["Heading4"]),
        Paragraph("Contract A", styles["Heading4"]),
        Paragraph("Contract B", styles["Heading4"])
    ]]
    
    for point in comparison_result.get('key_differences', []):
        diff_data.append([
            Paragraph(point.get('category', ''), small_style),
            Paragraph(point.get('risk_assessment', ''), small_style),
            Paragraph(point.get('contract_a_observation', ''), small_style),
            Paragraph(point.get('contract_b_observation', ''), small_style)
        ])
        
    # Adjust column widths to fit page (Letter width ~612pt, margins ~72pt each side -> ~468pt usable)
    # [Category, Risk, A, B]
    diff_table = Table(diff_data, colWidths=[70, 130, 130, 130])
    diff_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#f0f0f0")),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('LEFTPADDING', (0, 0), (-1, -1), 4),
        ('RIGHTPADDING', (0, 0), (-1, -1), 4),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    story.append(diff_table)

    # --- Footer ---
    story.append(Spacer(1, 40))
    footer_style = ParagraphStyle('Footer', parent=styles['Normal'], fontSize=8, textColor=colors.gray)
    story.append(Paragraph("Generated by ShouldISignThis? AI Consensus Engine. Not legal advice.", footer_style))

    doc.build(story)
    buffer.seek(0)
    return buffer
